# Path to directory where images are located
path_directory_images: /Users/germanifold/Desktop/Germanifold/Python_Projects/Image_Classification/image-classification/data/01_raw/cell_images

# Parameters for splitting of training and validation dataframe
split_params:
  random_state: 42
  test_size_training: 0.2
  test_size_validation: 0.5

nn_training_params:
  batch_size: 64
  image_size: 224
  channels: 3
  learning_rate: 0.001
  training_metric: accuracy
  activation_function: relu
  epochs: 4